[package]
name = "highlight-bin"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "highlight"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.30", features = ["derive", "wrap_help"]}
clio = { version = "0.3.5", features = ["clap-parse"]}
highlight = {path = "../"}
