stages:
  - build
  - publish

build_job:
  stage: build
  image: oven/bun
  script:
    - bun install
    - bun run build-queries

publish_job:
  stage: publish
  image: oven/bun
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - bun install --frozen-lockfile
    - bunx jsr publish --token "$JSR_TOKEN"
