stages:
  - publish

publish_job:
  stage: publish
  image: homebrew/brew
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  before_script:
    - brew install python
    - brew install oven-sh/bun/bun
  script:
    - bun install --frozen-lockfile
    - bun run build-queries
    - bunx jsr publish --token "$JSR_TOKEN"
