stages:
  - deploy

variables:
  PROJECT_NAME: highlight
  TAP_REPO: noClaps/homebrew-tap

# Create formula and publish to tap
deploy_formula:
  stage: deploy
  image: ruby:latest
  rules:
    - when: manual
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"

    # Set vars for formula URLs - use your project's actual hosting location
    - RELEASE_URL="https://gitlab.com/$CI_PROJECT_PATH/-/archive/$CI_COMMIT_TAG/$PROJECT_NAME-$CI_COMMIT_TAG.tar.gz"
    - curl $RELEASE_URL --output $PROJECT_NAME.tar.gz
    - ls
    - SHA256_CHECKSUM=$(sha256sum highlight.tar.gz | awk '{print $1}')

    # Create the formula file with bottles for multiple platforms
    - |
      cat > $PROJECT_NAME.rb << EOF
      class YourProject < Formula
        desc "A syntax highlighting CLI tool that uses Tree-sitter"
        homepage "https://gitlab.com/noClaps/highlight"
        url "$RELEASE_URL"
        sha256 "$SHA256_CHECKSUM"
        license "0BSD" # or whatever license you use

        depends_on "rust" => :build

        def install
          system "cargo", "install", "--locked", "--root", prefix, "--path", "bin"
        end

        test do
          # Add a test command to verify installation worked
          assert_match "version", shell_output("#{bin}/your-project --version")
        end
      end
      EOF

    # Clone tap repo using HTTPS with token and update formula
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/${TAP_REPO}.git tap
    - cp $PROJECT_NAME.rb tap/
    - cd tap
    - git add $PROJECT_NAME.rb
    - git commit -m "Update $PROJECT_NAME to $CI_COMMIT_TAG"
    - git push https://oauth2:${GITHUB_TOKEN}@github.com/${TAP_REPO}.git
