fg = "#fff"
bg = "#111"

[line_numbers]
color = "#888"
right_space = 2

[highlights]
attribute = {color = "#ac8e68", font_weight = 500}
boolean = {color = "#ff375f", font_weight = 700}
comment = {color = "#98989d", font_weight = 500}
"comment.doc" = {color= "#98989d"}
constant = {color = "#6ac4dc", font_weight = 500}
constructor = {color = "#66d4cf", font_weight = 500}
enum = {color = "#66d4cf", font_weight = 500}
emphasis = {color = "#5ac8f5", font_style = "italic"}
"emphasis.strong" = {color = "#5ac8f5", font_weight = 700}
function = {color = "#66d4cf", font_weight = 500 }
keyword= {color= "#ff375f", font_weight = 700}
label = {color= "#98989d", font_weight= 700}
"link.text" = {color = "#0a84ff", font_weight = 500}
"link.uri" = { color= "#0a84ff", font_weight = 500}
link_text = {color = "#ff9f0a", font_weight = 500}
link_uri = {color = "#0a84ff", font_weight = 500}
number = {color = "#ffd60a", font_weight = 500}
operator = {color = "#98989d", font_weight = 500}
preproc = {color = "#ff9f0a", font_weight = 500}
property = {color = "#6ac4dc", font_weight = 500}
"punctuation.bracket" = {color = "#98989d", font_weight= 500}
"punctuation.list_marker" = {color = "#ac8e68", font_weight = 500}
string = {color = "#ff9f0a", font_weight = 500}
"string.special" = {color = "#ff9f0a", font_weight = 500}
"string.special.symbol" = {color = "#ffd60a", font_weight = 500}
tag = {color = "#ff375f", font_weight = 700}
"text.literal"= {color = "#ff9f0a", font_weight = 500}
title= {color = "#98989d", font_weight = 700}
type= {color = "#5ac8f5", font_weight = 500}
"type.builtin"= {color = "#5ac8f5", font_weight = 500}
variable= {color = "#fff", font_weight = 500}
