on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        versions:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.versions.os }}
    name: ${{ matrix.versions.os }}-${{ matrix.versions.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.versions.target }}
      - uses: mlugg/setup-zig@v1
      - run: bun install
      - run: bun run build --target ${{ matrix.versions.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: highlight-${{ matrix.versions.target }}
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bunx jsr publish
