on:
  push:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz -O wasi-sdk.tar.gz
      - run: tar -xf wasi-sdk.tar.gz
      - run: |
          ls -al ./wasi-sdk/bin
          ls -al ./wasi-sdk/share/wasi-sysroot
      - run: rustup target add wasm32-wasip1
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: |
          export CC="./wasi-sdk/bin/clang"
          export WASI_SYSROOT="./wasi-sdk/share/wasi-sysroot"
          bun run build --target wasm32-wasip1
          ls -al .
      - uses: actions/upload-artifact@v4
        with:
          path: dist/
